# Generated by Django 4.2.16 on 2024-11-25 02:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user_id',
            field=models.IntegerField(default=uuid.uuid4, editable=False),
        ),
    ]
