# Generated by Django 4.2.16 on 2024-11-25 03:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_player_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user_id',
            field=models.IntegerField(default=uuid.uuid4),
        ),
    ]
