# Generated by Django 4.2.16 on 2024-11-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_player_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
